### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by ssorgatem** [ssorgatem/Octoprint-Filament-Reloaded#11]
Octoprint is great, but with Klipper there are better performing alternatives.

Klipper itself can manage what this plugin does, and so I've stopped using Octoprint altogether, for the foreseeable future.

I may still do some bug fixes if they are easy, but I won't be able tot est this plugin extensively.

Therefore I'm looking for a new maintainer.

**Comment by nickmitchko** [comment]
Closed per changed ownership

See here: https://github.com/OctoPrint/plugins.octoprint.org/issues/687
