### ISSUE TITLE
Issue an m600?

### ISSUE THREAD

**Issue by jtannenba** [ssorgatem/Octoprint-Filament-Reloaded#12]
When my printer runs out of filament, it just notifies Octoprint and stops, making it almost impossible to remove the filament.  Can we issue a m600 or other commands to unload the filament?

**Comment by nickmitchko** [comment]
@jtannenba Out of Filament GCODE can issue any GCODE to the printer when you run out of filament. I'd advise against issuing an [m600](https://marlinfw.org/docs/gcode/M600.html) in-case you are not near the printer at that moment.

![image](https://user-images.githubusercontent.com/7769991/151637659-d4c8fa31-adfc-4208-ab17-744644897495.png)

**Comment by jtannenba** [comment]
This was a long time ago.  Everything is working fine now.
Thank you
