### ISSUE TITLE
Documentation Question - Pause Function

### ISSUE THREAD

**Issue by enz1ey** [ssorgatem/Octoprint-Filament-Reloaded#17]
Just wondering, because the documentation is kind of ambiguous... When I tick the "Pause print when out of filament" checkbox, is this functionally the same as clicking the "pause" button in OctoPrint? And therefore my "After print job is paused" GCODE script in the settings being ran?

Or does this plugin send its own GCODE command to pause the print?

To clarify, my GCODE text box in the plugin settings is empty, I only have the pause checkbox enabled.

**Comment by nickmitchko** [comment]
Good question, let me dig into the code and check.

**Comment by nickmitchko** [comment]
In the settings, here is how it works:

- This selection will call "Octoprint Pause" as configured in the main settings ![image](https://user-images.githubusercontent.com/7769991/223181573-d86762d7-7588-48b3-874e-fa92f5501a7d.png)
- If you populate the "Out of Filament GCODE" it will send that gcode on out of filament. 
![image](https://user-images.githubusercontent.com/7769991/223182044-62023ba9-b70a-4744-8810-332b242c0230.png)

I will think about changing the names for clarity.

[Reference](https://github.com/nickmitchko/Octoprint-Filament-Reloaded/blob/3983bb414431937e5eee856cbdf53bd3ddd32245/octoprint_filamentreload/__init__.py#L271-L276)
