### ISSUE TITLE
Filament runout sensor icon not updating in touchui.

### ISSUE THREAD

**Issue by smcallis77** [ssorgatem/Octoprint-Filament-Reloaded#5]
My filament sensor is working well. Using the chrome interface (non touchui) the runout sensor updates in the navbar as per below.
![image](https://user-images.githubusercontent.com/31378549/95536058-c20b5880-0a35-11eb-949f-f1bef61d89cf.png)
 However, in the touchui interface the icon shows as per below.

![image](https://user-images.githubusercontent.com/31378549/95536304-70af9900-0a36-11eb-8963-6fc0815cb6dd.png)

**Comment by ssorgatem** [comment]
I suspect this may be due to touchui changing the icons?
I really have no idea.
I opened an issue on TouchUI's github to get some help

**Comment by nickmitchko** [comment]
Touch UI applies their own class overrides to these jinja templates. It should be as easy as adding in the class overrides into the jinja template. I'll take a look

**Comment by nickmitchko** [comment]
Update; we can define a less variable to work with OctoprintUI without much change to the plugin or JS.

Example here: [PSU Control Less Variables](https://github.com/kantlivelong/OctoPrint-PSUControl/blob/master/octoprint_psucontrol/static/less/psucontrol.less)

**Comment by nickmitchko** [comment]
I believe the latest version has these changes for touchUI to work. Let me know if it doesn't.
