### ISSUE TITLE
Question: Supported Filament Sensors

### ISSUE THREAD

**Issue by joshuajmlee** [ssorgatem/Octoprint-Filament-Reloaded#6]
I can't find any lists or any documentation anywhere to answer this question, so I'm hoping this is a good place to ask. Does anyone have a list of sensors that the raspberry pi and octoprint support for this plugin?

**Comment by ssorgatem** [comment]
Anything that opens or closes a circuit is supported.
You just need to wire it properly and configure it accordingly (the pullup/pulldown resistor setting + whether it is a normally open or normally closed sensor).

**Comment by joshuajmlee** [comment]
> Anything that opens or closes a circuit is supported.
> You just need to wire it properly and configure it accordingly (the pullup/pulldown resistor setting + whether it is a normally open or normally closed sensor).

Perfect, thank you!
