### ISSUE TITLE
Doesn't pause when printing from SD

### ISSUE THREAD

**Issue by ssorgatem** [ssorgatem/Octoprint-Filament-Reloaded#8]
Apparentlymit doesn't check the sensor when printing from the printer's SD.

**Comment by sethvoltz** [comment]
This is a plugin for Octoprint, it can only control Octoprint itself, not the printer.

**Comment by nickmitchko** [comment]
Might be out of scope of this plugin as generally printing from SD is self-encapsulated. Worth looking into [M24](https://marlinfw.org/docs/gcode/M024.html)/[M25](https://marlinfw.org/docs/gcode/M025.html) on SD printing
